package io.sqm.dbit.sqlserver;

enum SqlServerLiveFeature {
    BRACKET_IDENTIFIERS,
    TOP,
    TOP_PERCENT,
    TOP_WITH_TIES,
    OFFSET_FETCH,
    TABLE_LOCK_HINT_NOLOCK,
    TABLE_LOCK_HINT_UPDLOCK,
    TABLE_LOCK_HINT_HOLDLOCK,
    LEN,
    DATEADD,
    DATEDIFF,
    ISNULL,
    STRING_AGG,
    INSERT_OUTPUT,
    UPDATE_OUTPUT_INTO,
    DELETE_OUTPUT,
    MERGE_MATCHED_UPDATE,
    MERGE_MATCHED_DELETE,
    MERGE_NOT_MATCHED_INSERT,
    MERGE_NOT_MATCHED_BY_SOURCE_UPDATE,
    MERGE_NOT_MATCHED_BY_SOURCE_DELETE,
    MERGE_CLAUSE_PREDICATE,
    MERGE_TOP,
    MERGE_TOP_PERCENT
}
