package io.sqm.dbit.mysql;

enum MySqlLiveFeature {
    INSERT_IGNORE,
    ON_DUPLICATE_KEY_UPDATE,
    REPLACE_INTO,
    JOINED_UPDATE,
    JOINED_UPDATE_QUALIFIED_TARGET,
    INDEX_HINTS,
    DELETE_USING_JOIN,
    OPTIMIZER_HINT_COMMENT,
    STRAIGHT_JOIN,
    JSON_EXTRACT,
    DATE_ADD_INTERVAL,
    CONCAT_WS
}