package io.sqm.dbit.postgresql;

enum PostgresLiveFeature {
    DISTINCT_ON,
    INSERT_RETURNING,
    UPDATE_FROM,
    DELETE_USING,
    ON_CONFLICT_DO_NOTHING,
    ON_CONFLICT_DO_UPDATE,
    WRITABLE_CTE_INSERT_RETURNING,
    WRITABLE_CTE_UPDATE_RETURNING,
    WRITABLE_CTE_DELETE_RETURNING,
    MERGE_MATCHED_UPDATE,
    MERGE_MATCHED_DELETE,
    MERGE_NOT_MATCHED_INSERT,
    MERGE_NOT_MATCHED_BY_SOURCE_DELETE,
    MERGE_MATCHED_DO_NOTHING,
    MERGE_NOT_MATCHED_DO_NOTHING,
    MERGE_NOT_MATCHED_BY_SOURCE_DO_NOTHING,
    MERGE_RETURNING
}
