package io.sqm.dbit.oracle;

enum OracleLiveFeature {
    DOUBLE_QUOTED_IDENTIFIERS,
    TABLE_ALIAS,
    DERIVED_TABLE_ALIAS,
    LATERAL_DERIVED_TABLE,
    FETCH_FIRST,
    OFFSET_FETCH,
    OPTIMIZER_HINT_COMMENT,
    DML_OPTIMIZER_HINT_COMMENT,
    INSERT,
    UPDATE,
    DELETE,
    RETURNING_INTO,
    MERGE_MATCHED_UPDATE,
    MERGE_NOT_MATCHED_INSERT,
    SEQUENCE_NEXT_VALUE,
    SEQUENCE_CURRENT_VALUE,
    HIERARCHICAL_QUERY,
    PIVOT,
    UNPIVOT,
    JSON_TABLE,
    FLASHBACK_AS_OF_TIMESTAMP,
    TABLE_PARTITION,
    TABLE_SAMPLING,
    AT_TIME_ZONE,
    LOCK_WAIT
}
